version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx:
    container_name: nginx
#    environment:
#      MYSQL_DATABASE: 'db'
    build:
      context: ./nginx
    ports:
      - '888:80'
    volumes:
      - ..:/var/www:rw

  mysql:
    container_name: my_db
    build:
      context: ./mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql/var/lib/mysql:/var/lib/mysql:delegated

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    #      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 7777:8080