version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx:
    container_name: nginx
    environment:
      MYSQL_DATABASE: 'db'
    build:
      context: ./nginx
    ports:
      - '888:80'
    volumes:
      - ..:/var/www:rw

  qwe:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'nhl'
      POSTGRES_USER: 'nhl'
      POSTGRES_PASSWORD: 'nhl'
    volumes:
      - nhl_db_data:/var/lib/postgresql/data:rw

volumes:
  nhl_db_data: